---
settings:
parallel: true

driver: vagrant
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: server
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-graphite::master]
    - recipe[collectd::server]
    - recipe[ktc-collectd::client_graphite]
  attributes:
    ha_disabled: true
    graphite:
      server_address: 127.0.0.1
    etcd:
      addr: 127.0.0.1
      peer_addr: 127.0.0.1
      servers:
        - 127.0.0.1

- name: client
  run_list:
    - recipe[ktc-testing]
    - recipe[collectd_test]
