---
settings:
parallel: true

driver: vagrant
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: server
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[collectd::server]
    - recipe[ktc-collectd::client_graphite]
  attributes:
    ha_disabled: true
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001'
      servers:
        - 127.0.0.1

- name: client
  run_list:
    - recipe[ktc-testing]
    - recipe[collectd_test]
